// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyThF7uv_cZRSa-84BdVQlZT_RKRN4jF4',
    appId: '1:888959421731:web:aa78ec4f5184f722855096',
    messagingSenderId: '888959421731',
    projectId: 'doc-app-282ce',
    authDomain: 'doc-app-282ce.firebaseapp.com',
    storageBucket: 'doc-app-282ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9qPjeUT5oeQu3Zg4FOWl5RR_WoG68SY',
    appId: '1:888959421731:android:33f126f538adbe53855096',
    messagingSenderId: '888959421731',
    projectId: 'doc-app-282ce',
    storageBucket: 'doc-app-282ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGiaL_MjJtE4tuNI1kE-fOYicggzGdY9U',
    appId: '1:888959421731:ios:d347de2cb8d591cd855096',
    messagingSenderId: '888959421731',
    projectId: 'doc-app-282ce',
    storageBucket: 'doc-app-282ce.appspot.com',
    iosBundleId: 'com.example.docApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGiaL_MjJtE4tuNI1kE-fOYicggzGdY9U',
    appId: '1:888959421731:ios:d347de2cb8d591cd855096',
    messagingSenderId: '888959421731',
    projectId: 'doc-app-282ce',
    storageBucket: 'doc-app-282ce.appspot.com',
    iosBundleId: 'com.example.docApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyThF7uv_cZRSa-84BdVQlZT_RKRN4jF4',
    appId: '1:888959421731:web:b0bcfec82c70096c855096',
    messagingSenderId: '888959421731',
    projectId: 'doc-app-282ce',
    authDomain: 'doc-app-282ce.firebaseapp.com',
    storageBucket: 'doc-app-282ce.appspot.com',
  );
}
